### ISSUE TITLE
bootstrap ubuntu bionic fails because of python3-pip package

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-bootstrap#53]
For ubuntu bionic, the python3-pip package has moved to repository universe. If you bootstrap a host with debops, the playbook fails because the universe repository is not added for ubuntu bionic:

```
failed: [gitlab-rn-node1] (item=[u'python3', u'python3-apt', u'python', u'python-apt', u'python3-httplib2', 
u'python3-pip', u'python3-setuptools', u'python3-pycurl', u'python3-virtualenv', u'python3-wheel', 
u'virtualenv', u'python-httplib2', u'python-pip', u'python-setuptools', u'python-pycurl', u'python-virtualenv', 
u'python-wheel']) => {"changed": false, "item": ["python3", "python3-apt", "python", "python-apt", 
"python3-httplib2", "python3-pip", "python3-setuptools", "python3-pycurl", "python3-virtualenv", 
"python3-wheel", "virtualenv", "python-httplib2", "python-pip", "python-setuptools", "python-pycurl", 
"python-virtualenv", "python-wheel"], "msg": "No package matching 'python3-pip' is available"}
```

It can be fixed by adding the following to debops.python/tasks/main.yml:
```
- name: add universe repository for bionic
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
  when: ansible_distribution_release == 'bionic'
```
Not sure if you want to solve it like this, else I'm willing to submit a PR with this solution. Pls let me know.
